require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/material_types", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MaterialType. As you add validations to MaterialType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MaterialType.create! valid_attributes
      get material_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      material_type = MaterialType.create! valid_attributes
      get material_type_url(material_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_material_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      material_type = MaterialType.create! valid_attributes
      get edit_material_type_url(material_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MaterialType" do
        expect {
          post material_types_url, params: { material_type: valid_attributes }
        }.to change(MaterialType, :count).by(1)
      end

      it "redirects to the created material_type" do
        post material_types_url, params: { material_type: valid_attributes }
        expect(response).to redirect_to(material_type_url(MaterialType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MaterialType" do
        expect {
          post material_types_url, params: { material_type: invalid_attributes }
        }.to change(MaterialType, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post material_types_url, params: { material_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested material_type" do
        material_type = MaterialType.create! valid_attributes
        patch material_type_url(material_type), params: { material_type: new_attributes }
        material_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the material_type" do
        material_type = MaterialType.create! valid_attributes
        patch material_type_url(material_type), params: { material_type: new_attributes }
        material_type.reload
        expect(response).to redirect_to(material_type_url(material_type))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        material_type = MaterialType.create! valid_attributes
        patch material_type_url(material_type), params: { material_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested material_type" do
      material_type = MaterialType.create! valid_attributes
      expect {
        delete material_type_url(material_type)
      }.to change(MaterialType, :count).by(-1)
    end

    it "redirects to the material_types list" do
      material_type = MaterialType.create! valid_attributes
      delete material_type_url(material_type)
      expect(response).to redirect_to(material_types_url)
    end
  end
end
